refactor: runtime changed form node to bun

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -20,51 +20,47 @@ jobs:
       )
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repo
+      - name: 📥 Checkout Repo
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - name: Setup pnpm
-        run: npm install -g pnpm
-
-      - name: Setup Node.js with pnpm
-        uses: actions/setup-node@v4
+      - name: 🛠️ Setup Bun
+        uses: oven-sh/setup-bun@v2
         with:
-          node-version: lts/*
-          cache: 'pnpm'
+          bun-version: latest
 
-      - name: Install Dependencies
-        run: pnpm install
+      - name: 📦 Install Dependencies
+        run: bun install --frozen-lockfile
 
-      - name: Build Artifacts
-        run: pnpm build
+      - name: ⚙️ Build Artifacts
+        run: bun run build
 
-      # - name: Run Tests
-      #   run: pnpm test
+      # - name: ✅ Test Code
+      #   run: bun run test
 
-      - name: Lint Code
-        run: pnpm lint || echo "Linting failed, but continuing"
+      - name: 🧹 Lint Code
+        run: bun run lint || echo "Linting failed, but continuing"
 
-      - name: Format Code
-        run: pnpm format
+      - name: 🧼 Format Code
+        run: bun run format
 
-      - name: AutoFix Code
+      - name: 🤖 AutoFix Code
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
           commit_message: 'chore: apply code fixes [skip ci]'
 
-      - name: Bump Version
+      - name: 🏷️ Bump Version
         id: bump_version
         run: |
           rm -f CHANGELOG.md
-          pnpx changelogen@latest --bump
+          bunx changelogen@latest --bump
           CHLOG=$(cat CHANGELOG.md)
           echo -e "CHANGELOG_CONTENT<<EOF\n${CHLOG}\nEOF" >> $GITHUB_ENV
           git reset --hard
-          pnpx changelogen@latest --bump
+          bunx changelogen@latest --bump
 
-      - name: Create or Update Pull Request
+      - name: 🔀 Create or Update Pull Request
         uses: peter-evans/create-pull-request@v7
         with:
           commit-message: 'ci(release): update version'
