feat: add initial setup for UnAscii Playground with Docker support and UI components

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -14,10 +14,10 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Setup Corepack for pnpm
+      - name: Setup pnpm
         run: npm i -g pnpm
 
-      - name: Setup Node.js with Corepack
+      - name: Setup Node.js with pnpm
         uses: actions/setup-node@v4
         with:
           node-version: lts/*
@@ -45,3 +45,38 @@ jobs:
           commit: 'chore(release): update version'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  build-web:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Change Working Directory
+        run: cd playground/web
+
+      - name: Setup pnpm
+        run: npm i -g pnpm
+
+      - name: Setup Node.js with pnpm
+        uses: actions/setup-node@v4
+        with:
+          node-version: lts/*
+          cache: 'pnpm'
+
+      - name: Install Dependencies
+        run: pnpm install
+
+      - name: Bulid Artifacts
+        run: pnpm build
+
+      # - name: Run Tests
+      #   run: pnpm test
+
+      - name: Lint Code
+        run: pnpm lint || echo "Linting failed, but continuing"
+
+      # - name: Format Code
+      #   run: pnpm format
